# Generated by Django 4.0.5 on 2025-03-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('image_binary', models.BinaryField(blank=True, null=True)),
                ('image_file_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
