# Generated by Django 4.0.5 on 2025-04-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetting',
            name='image_file_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
