# Generated by Django 4.0.5 on 2025-03-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_todoitem_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='picture',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
