# Generated by Django 4.0.5 on 2025-05-08 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_bulkimageupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulkimageupload',
            old_name='created_time',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='bulkimageupload',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='bulkimageupload',
            name='images_binary',
        ),
        migrations.RemoveField(
            model_name='bulkimageupload',
            name='name',
        ),
        migrations.CreateModel(
            name='BulkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_binary', models.BinaryField()),
                ('image_file_name', models.CharField(max_length=255)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.bulkimageupload')),
            ],
        ),
    ]
