# Generated by Django 4.0.5 on 2025-03-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_todoitem_picture_todoitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='image',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
