# Generated by Django 4.0.5 on 2025-03-13 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_todoitem_image_binary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='picture',
        ),
    ]
