# Generated by Django 4.0.5 on 2025-06-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_ipknowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipknowledge',
            name='image_file_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
