# Generated by Django 4.0.5 on 2025-03-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_todoitem_image_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='image_file_name',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
