# Generated by Django 4.0.5 on 2025-03-13 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_todoitem_image_file_name_todoitem_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='picture',
        ),
    ]
