# Generated by Django 4.0.5 on 2025-03-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_todoitem_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='image_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
